In [1]:
%load_ext autoreload
# %matplotlib widget

In [159]:
%autoreload 2
import datasetpy as dp
print( dir(dp) )
from uncertainties import unumpy as un
import numpy as np

['Array', 'Coord', 'Data', '__builtins__', '__cached__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'arange', 'broadcast', 'eV', 'genfromcsv', 'genfromroot', 'keV', 'np', 'plot', 'plt', 're', 'read_header', 'uproot', 'ureg']


In [30]:
a = dp.arange( "range", 0, 1, .1, dim = "E", units = "eV", std_devs = .01 )
a

    range	(E)[eV]
 [0.00±0.01 0.10±0.01 0.20±0.01 0.30±0.01 0.40±0.01 0.50±0.01 0.60±0.01
 0.70±0.01 0.80±0.01 0.90±0.01]

In [15]:
b = dp.arange( "range", 0, 1, .1, dim = "E", units = "keV", std_devs = .005 )
print( b )

    range	(E)[keV]
 [0.000±0.005 0.100±0.005 0.200±0.005 0.300±0.005 0.400±0.005 0.500±0.005
 0.600±0.005 0.700±0.005 0.800±0.005 0.900±0.005]


In [36]:
a + b

    None	(E)[eV]
 [0±5 100±5 200±5 300±5 400±5 500±5 601±5 701±5 801±5 901±5]

In [37]:
a + 2

In [154]:
dp.broadcast(a, b)
a*b

    None	(E)[keV ** 2]
 [0.0±0 (1.0±0.1)×10⁻⁵ (4.0±0.2)×10⁻⁵ (9.0±0.3)×10⁻⁵ 0.000160±0.000004
 0.000250±0.000006 0.000360±0.000007 0.000490±0.000008 0.000640±0.000009
 0.00081±0.00001]

In [64]:
c = dp.Array( "range", [[0, 1, .1],[2,3,4]], dims = ["y", "x"], units = "m", std_devs = .001 )
c

    range	(y, x)[m]
 [[0.000±0.001 1.000±0.001 0.100±0.001]
 [2.000±0.001 3.000±0.001 4.000±0.001]]

In [133]:
a * c

    None	(x, y, E)[eV * m]
 [[[0.0±0 0.0000±0.0001 0.0000±0.0002 ... 0.0000±0.0007 0.0000±0.0008
   0.0000±0.0009]
  [0.00±0.02 0.20±0.02 0.40±0.02 ... 1.40±0.02 1.60±0.02 1.80±0.02]]

 [[0.00±0.01 0.10±0.01 0.20±0.01 ... 0.70±0.01 0.80±0.01 0.90±0.01]
  [0.00±0.03 0.30±0.03 0.60±0.03 ... 2.10±0.03 2.40±0.03 2.70±0.03]]

 [[0.000±0.001 0.010±0.001 0.020±0.001 ... 0.070±0.001 0.080±0.001
   0.090±0.001]
  [0.00±0.04 0.40±0.04 0.80±0.04 ... 2.80±0.04 3.20±0.04 3.60±0.04]]]

In [162]:
print( type(2*dp.keV) )
(2.*dp.keV) * a

<class 'pint.quantity.build_quantity_class.<locals>.Quantity'>
other 2.0 <class 'float'>
self [0.0+/-0.01 0.1+/-0.01 0.2+/-0.01 0.30000000000000004+/-0.01 0.4+/-0.01 0.5+/-0.01 0.6000000000000001+/-0.01 0.7000000000000001+/-0.01 0.8+/-0.01 0.9+/-0.01] eV <class 'pint.quantity.build_quantity_class.<locals>.Quantity'>
self [0.0+/-0.02 0.2+/-0.02 0.4+/-0.02 0.6000000000000001+/-0.02 0.8+/-0.02 1.0+/-0.02 1.2000000000000002+/-0.02 1.4000000000000001+/-0.02 1.6+/-0.02 1.8+/-0.02] eV <class 'pint.quantity.build_quantity_class.<locals>.Quantity'>
other 1.6021766339999998e-13 <class 'float'>


None	(E)[eV]
 [0.00±0.02 0.20±0.02 0.40±0.02 0.60±0.02 0.80±0.02 1.00±0.02 1.20±0.02
 1.40±0.02 1.60±0.02 1.80±0.02] <Unit('kiloelectron_volt')>

In [13]:
import numpy as np

dp.Coord( 
    name = "my_coord", 
    data = np.arange(0,1,.1),
    dims = "my_dim"
)

<Coord>	(my_dim: 10)
    my_coord	(my_dim) []
[0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
Attributes:

In [14]:
from uncertainties import unumpy as un

dp.Coord(
    name = "uncertanties",
    data = un.uarray( np.arange(0,1,.01), 0 ),
    dims = "my_dim"
)

<Coord>	(my_dim: 100)
    uncertanties	(my_dim) []
[0.0 0.01 0.02 ... 0.97 0.98 0.99]
Attributes:

In [15]:
dp.Coord(
    name = "uncertanties",
    data = np.arange(0,1,.1),
    data_err = 0.,
    dims = "my_dim"
)

<Coord>	(my_dim: 10)
    uncertanties	(my_dim) []
[0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

In [16]:
dp.Coord( 
    name = "my_coord", 
    data = [1,2,3,4],
    dims = "my_dim"
)

<Coord>	(my_dim: 4)
    my_coord	(my_dim) []
[1.0 2.0 3.0 4.0]
Attributes:

In [17]:
import pint
from pint import UnitRegistry
ureg = UnitRegistry()

dp.Coord( 
    name = "my_coord", 
    data = np.arange(0, 1, .1),
    units = "eV",
    dims = "my_dim"
)

<Coord>	(my_dim: 10)
    my_coord	(my_dim) [eV]
[0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
Attributes:

In [34]:
a = dp.Array(
    name = "array",
    data = np.arange(0, 1, .1),
    err = 0.1,
    units = "keV",
    coords = dp.Coord(
        name = "coord",
        data = np.arange(0, 1, .1),
        err = .05555,
        units = "m**2",
        dims = "L",
        extra_attr = "4"
    ),
    long_name = "long_name"
)
print( a.coords )
print( "units", a.u )
print( a )
a.plot()

{'coord': <Coord>	(L: 10)
    coord	(L) [m²]
[0.00±0.06 0.10±0.06 0.20±0.06 0.30±0.06 0.40±0.06 0.50±0.06 0.60±0.06
 0.70±0.06 0.80±0.06 0.90±0.06]
}
units keV
<Array>	()
    array	(L) [keV]
[0.0±0.1 0.1±0.1 0.2±0.1 0.3±0.1 0.4±0.1 0.5±0.1 0.6±0.1 0.7±0.1 0.8±0.1
 0.9±0.1]
Coordinates:
    coord	(L) [m²]
[0.00±0.06 0.10±0.06 0.20±0.06 0.30±0.06 0.40±0.06 0.50±0.06 0.60±0.06
 0.70±0.06 0.80±0.06 0.90±0.06]



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [95]:
reactorFlux = dp.genfromcsv("data/reactorFlux.csv", dims="E")
print( reactorFlux.coords )
print( reactorFlux )
reactorFlux.E_nu.latex = r"$E_\nu$"
dp.plot( reactorFlux )

[<Coord>	(E: 400)
    E_nu	(E) [MeV]
[0.01 0.02 0.03 ... 3.98 3.99 4.0]
]
<Array>	(E: 400)
    flux	(E) [count/MeV/cm²/s]
[1.553e+11 6.00503e+11 1.20517e+12 ... 3.30249e+11 3.27263e+11 3.24299e+11]
Coordinates:
    E_nu	(E) [MeV]
[0.01 0.02 0.03 ... 3.98 3.99 4.0]



/home/mota/.local/lib/python3.6/site-packages/ipywidgets/widgets/widget.py:412: DeprecationWarning: Passing unrecoginized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
/home/mota/.local/lib/python3.6/site-packages/ipywidgets/widgets/widget.py:412: DeprecationWarning: Passing unrecoginized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

/home/mota/.local/lib/python3.6/site-packages/numpy/lib/function_base.py:2190: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  for a in args]


In [103]:
import run2019
dataset = dp.genfromroot(
    name = "run2019",
    fpath = run2019.data_files,
    treename = "hitSumm",
    branches = [
        {"readout_noise": "rawNoise/gain3Peaks", "units": "keV", "latex": r"$\sigma_\text{raw}$"},
        {"dark_current": "rawDC", "latex": r"$\lambda_\text{raw}$"},
        {"hdu": "ohdu"},
        "runID",
    ],
    cut = str( run2019.on_excl*run2019.excluded_ohdu )
)
print( dataset )


{}
{}
{}
{}


AttributeError: 'Array' object has no attribute '_dims'

In [37]:
!py.test datasetpy/tests.py

============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/mota/connie/CONNIEtools
plugins: anyio-3.2.1
collected 4 items                                                              

datasetpy/tests.py ....                                                  [100%]

=============================== warnings summary ===============================
../../.local/lib/python3.6/site-packages/past/builtins/misc.py:45
  /home/mota/.local/lib/python3.6/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import reload

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 4 passed, 1 warning in 15.80s =========================
